### PR TITLE
Use React 16 & Remove PropsTable Script

### LINKED ISSUE #85: Update package.json Template to Use React v16 Dependencies
### Description of Issue
In the [template package.json file](https://github.com/cerner/generator-terra-module/blob/master/generators/app/templates/package.json#L23-L35), React v15 and React v15 `terra-core` components are used as dependencies. These should be updated to their React 16 versions.

screen shot 2018-03-01 at 10 20 22 am

#### Generator Version
1.6.0

#### Node Version
8.9.2

### Steps to Reproduce the Issue
1. [Scaffold a new component](https://github.com/cerner/generator-terra-module#getting-started)
1. Look at new component package.json dependencies

### Expected Outcomes
- Dependency React version should be v16
- Dependency Terra components should be React v16 versions

### PR DESCRIPTION
**Pull request by emilyrohrbough**
### Summary
Resolves #85

### CODE REVIEW

**Comment by mjhenkes** [comment]
do you want to switch the generator for terra-clinical to the newer terra-framework style?

File: test/app.js [hunk 1]
```diff
@@ -25,7 +25,10 @@ describe('generator-terra-module:app', function () {
       });
 
       it('creates files', function () {
-        const examplePath = repositoryName === 'terra-framework' ? '-monster-cookies/examples/Index.site-page.jsx' : '-site/src/examples/monster-cookies/Index.jsx';
+        let examplePath = '-site/src/examples/monster-cookies/Index.jsx';
+        if (repositoryName === 'terra-framework' || repositoryName === 'terra-clinical') {
+          examplePath = '-monster-cookies/examples/Index.site-page.jsx';
```
Comment (StephenEsser) [inline test/app.js]: Cookie Monstert
